<?php

$list = array(
    /* INVOCATEUR */
    'summonerLevel' => 'Niveau d\'invocateur',
    'summonerName' => 'Nom d\'invocateur',
    /* COMBAT */
    'kills' => 'Éliminations',
    'deaths' => 'Morts',
    'assists' => 'Assistances',
    'longestTimeSpentLiving' => 'Temps le plus long en vie',
    'totalTimeSpentDead' => 'Total du temps passé mort',
    'largestKillingSpree' => 'Plus grosse série d\'éliminations',
    'largestMultiKill' => 'Plus grosse élimination multiple',
    'unrealKills' => 'Éliminations multiple',
    'killingSprees' => 'Série d\'éliminations',
    'bountyLevel' => 'Niveau de prime d\'élimination maximale',
    'firstBloodKill' => 'Premier sang',
    'firstBloodAssist' => 'Assistance sur le premier sang',
    'timeCCingOthers' => 'Score de contrôle de foule',
    'totalTimeCCDealt' => 'Durée total des contrôles de foules',
    'doubleKills' => 'Doublé',
    'tripleKills' => 'Triplé',
    'quadraKills' => 'Quadruplé',
    'pentaKills' => 'Quintuplé',
    /* INFOS CHAMPIONS */
    'champLevel' => 'Niveau du champion',
    'championName' => 'Nom du champion',
    'champExperience' => 'Expérience du champion',
    /* DEGATS INFLIGES */
    'totalDamageDealtToChampions' => 'Dégats totaux aux champions',
    'physicalDamageDealtToChampions' => 'Dégâts physiques aux champions',
    'magicDamageDealtToChampions' => 'Dégâts magiques aux champions',
    'trueDamageDealtToChampions' => 'Dégats brut totaux aux champions',
    'totalDamageDealt' => 'Dégats totaux infligés',
    'physicalDamageDealt' => 'Dégâts physiques infligés',
    'magicDamageDealt' => 'Dégâts magiques infligés',
    'trueDamageDealt' => 'Dégats brut infligés',
    'largestCriticalStrike' => 'Coup critique maximal',
    'damageDealtToTurrets' => 'Dégâts infligés aux tours',
    'damageDealtToObjectives' => 'Dégâts infligés aux objectifs',
    'damageDealtToBuildings' => 'Dégâts infligés aux batiments',
    /* DEGATS SUBIS ET SOIN */
    'totalHeal' => 'Soin totaux',
    'totalDamageTaken' => 'Dégats totaux subis',
    'physicalDamageTaken' => 'Dégâts physiques subis',
    'magicDamageTaken' => 'Dégâts magiques subis',
    'trueDamageTaken' => 'Dégats brut subis',
    'damageSelfMitigated' => 'Dégats réduis sur soi',
    'totalDamageShieldedOnTeammates' => 'Dégats réduit par les boucliers',
    'totalHealsOnTeammates' => 'Total des soins sur les alliés',
    'totalUnitsHealed' => 'Alliés soignés',
    /* VISION */
    'visionScore' => 'Score de vision',
    'wardsPlaced' => 'Balise placée',
    'wardsKilled' => 'Balise détruite',
    'visionWardsBoughtInGame' => 'Balise de contrôle achetés',
    'detectorWardsPlaced' => 'detectorWardPlaced',
    /* REVENUS */
    'goldEarned' => 'Or gagné',
    'goldSpent' => 'Or dépensées' ,
    'totalMinionsKilled' => 'Sbires tué',
    'neutralMinionsKilled' => 'Monstres tués',
    /* OBJETS */
    'item0' => 'Objet 1',
    'item1' => 'Objet 2',
    'item2' => 'Objet 3',
    'item3' => 'Objet 4',
    'item4' => 'Objet 5',
    'item5' => 'Objet 6',
    'item6' => 'Relique',
    'consumablesPurchased' => 'Consommables achetés',
    'itemsPurchased' => 'Objets achetés',
    /* SORTS */
    'spell1Casts' => 'Sort 1 lancé',
    'spell2Casts' => 'Sort 2 lancé',
    'spell3Casts' => 'Sort 3 lancé',
    'spell4Casts' => 'Sort 4 lancé',
    'summoner1Id' => 'Id sort d\'invocateur 1',
    'summoner1Casts' => 'Sort d\'invocateur 1 lancé',
    'summoner2Id' => 'Id sort d\'invocateur 2',
    'summoner2Casts' => 'Sort d\'invocateur 2 lancé',
    /* OBJECTIFS */
    'turretKills' => 'Tourelles Détruits',
    'turretsLost' => 'Tours perdus',
    'firstTowerKill' => 'Destruction première tour',
    'firstTowerAssist' => 'Assistance destruction première tour',
    'inhibitorKills' => 'Inhibiteur détruit',
    'inhibitorsLost' => 'Inhibiteur perdu',
    'objectivesStolen' => 'Objectifs volés',
    'objectivesStolenAssists' => 'Assistance sur un objectif volé',
    'nexusKills' => 'Destruction du nexus',
    'nexusLost' => 'Nexus perdu',
    'dragonKills' => 'Dragons tués',
    'baronKills' => 'Baron nashor tué',
    /* PARTIE */
    'individualPosition' => 'Poste dans champ select',
    'lane' => 'Voie',
    'role' => 'Rôle',
    'teamPosition' => 'Rôle d\'équipe',
    'gameEndedInEarlySurrender' => 'Rédition anticipée',
    'gameEndedInSurrender' => 'Rédition',
    'teamEarlySurrendered' => 'Rédition anticipée de l\'équipe',
    'timePlayed' => 'Temps de jeu',
    'gameDuration' => 'Durée de la partie',
    'gameStartTimestamp' => 'Unix timestamp du début de la partie',
    'gameEndTimestamp' => 'Unix timestamp de la fin de la partie',
    'win' => 'Victoire',
    'matchId' => 'matchId',
);

file_put_contents('list.json', json_encode($list));
?>